import test from "node:test";import assert from "node:assert/strict";import net from "node:net";import os from "node:os";import path from "node:path";import fs from "node:fs";
import {authorizeToolCall} from "../dist/ipc-client.js";
const event={toolName:"invaros_probe_touch",params:{marker:"allow-case"},toolCallId:"tc"};
async function server(handler){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"ipc-client-")),sock=path.join(dir,"s"),connections=new Set();const s=net.createServer(c=>{connections.add(c);c.once("close",()=>connections.delete(c));handler(c)});await new Promise(r=>s.listen(sock,r));return {sock,close:()=>new Promise(r=>{for(const c of connections)c.destroy();s.close(()=>{fs.rmSync(dir,{recursive:true});r()})})};}
function response(req,change={}){return {...{protocol:"invaros.openclaw.authorization.v1",messageType:"authorization_response",requestId:req.requestId,toolCallId:req.toolCallId,decision:"ALLOW",reasonCode:"pilot.allowed_marker",message:"allowed",policyId:"pilot.openclaw.probe.v1",daemonPid:42},...change};}
test("valid framed allow and transmitted digest",async()=>{let params;const s=await server(sock=>{sock.once("data",data=>{const n=data.readUInt32BE();const req=JSON.parse(data.subarray(4,4+n));params=Buffer.from(JSON.stringify(req.params));const body=Buffer.from(JSON.stringify(response(req)));const h=Buffer.alloc(4);h.writeUInt32BE(body.length);sock.end(Buffer.concat([h,body]));})});const r=await authorizeToolCall(event,{socketPath:s.sock,requestId:"req"});assert.equal(r.response.decision,"ALLOW");assert.equal(r.paramsByteLength,params.length);await s.close()});
test("absent socket fails closed",async()=>await assert.rejects(authorizeToolCall(event,{socketPath:"/tmp/definitely-absent-invaros.sock",timeoutMs:50})));
test("partial, oversized, EOF, reset, malformed and timeout reject",async()=>{const cases=[sock=>sock.end(Buffer.from([0,0])),sock=>{const h=Buffer.alloc(4);h.writeUInt32BE(65537);sock.end(h)},sock=>sock.end(),sock=>sock.destroy(),sock=>{const b=Buffer.from("{}");const h=Buffer.alloc(4);h.writeUInt32BE(b.length);sock.end(Buffer.concat([h,b]))},()=>{}];for(const handler of cases){const s=await server(handler);await assert.rejects(authorizeToolCall(event,{socketPath:s.sock,timeoutMs:30}));await s.close();}});
test("correlation mismatch rejects",async()=>{const s=await server(sock=>sock.once("data",data=>{const n=data.readUInt32BE(),req=JSON.parse(data.subarray(4,4+n));const b=Buffer.from(JSON.stringify(response(req,{requestId:"wrong"}))),h=Buffer.alloc(4);h.writeUInt32BE(b.length);sock.end(Buffer.concat([h,b]))}));await assert.rejects(authorizeToolCall(event,{socketPath:s.sock,requestId:"req"}));await s.close()});
